### ISSUE TITLE
P4 APP.REQ - Database should update. Need to decided how...

### ISSUE THREAD

**Issue by savursool247** [ErrolKeith/CornerTeam#18]
"The file(s)/database should be updated (or recreated) either when you add, update, 
or remove documents from your set (of indexed documents), 
or just once when the program starts up and when it shuts down. "

**Comment by savursool247** [comment]
I think it currently depends on how we're gonna be coding the program, so we can decide this as we continue to code the application.

**Comment by savursool247** [comment]
@ErrolKeith @tswess 
currently, the only thing that updates is the Admin panel JList (when Admin button is clicked, the Jlist collects whatever is in the DB). Do we know where the files being searched by the user will be kept? Will users have these files locally? Or should they be packaged with the application?

**Comment by ErrolKeith** [comment]
I believe the user will add them and we don't need to add anything. We can have files in the program, but the path will be incorrect for the user locally compared to what the path may have been when we setup the program.

**Comment by ErrolKeith** [comment]
rebuild index will solve this issue, closing this since it correlates with another issue and will be solved by the already created rebuildIndex() method. the rebuildIndex method will keep the DB updated and persisted. Then at the end of the method we will add our buildIndex method that will create the inverted index for every file based on the names in the database.
